# Generated by Django 4.2.13 on 2024-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('kindle', models.BooleanField(null=True)),
                ('physical', models.BooleanField(null=True)),
                ('date_finished', models.DateField()),
                ('times_read', models.IntegerField()),
                ('year_published', models.PositiveIntegerField(null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='media.author')),
            ],
        ),
    ]
