# Generated by Django 4.2.13 on 2024-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title_reference',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
