# Generated by Django 4.2.13 on 2024-07-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_book_jpg_path_book_svg_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contains_spoilers',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='highlights_uploaded',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='notes_uploaded',
            field=models.BooleanField(null=True),
        ),
    ]
