# Generated by Django 4.2.13 on 2024-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='location',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
